package edu.pacific.comp55.starter;

public enum Goal {
		//Needs. Should be on a timer. If ignored partygoer incurs debuffs. Not used in class version.
		EATING, SLEEPING, 
		
		//Brewing goals seperated by what they're brewing and where.
		BREWING_POISON_WITCH, BREWING_ANTIDOTE_WITCH, BREWING_PERFUME_WITCH, BREWING_KO_WITCH,
		BREWING_POISON_CELLAR, BREWING_ANTIDOTE_CELLAR, BREWING_PERFUME_CELLAR, BREWING_KO_CELLAR,
		BREWING_POISON_APOTH, BREWING_ANTIDOTE_APOTH, BREWING_PERFUME_APOTH, BREWING_KO_APOTH,
		
		//Gathering goals. Need to make a wander function so A.I. wanders until it finds something of interest.
		RANSACK, GET_KNIFE, CRAFTING_LOCKPICK, CRAFTING_PISTOL, 
		GET_RIFLE, GET_SWORD, OOHSHINY, GOSSIPING, GET_FRAGRANT_PLANT_GREENHOUSE,
		GET_FRAGRANT_PLANT_OUTDOORS, GET_RITUAL_ITEM, GET_MEDICINAL_PLANT_GREENHOUSE, GET_MEDICINAL_PLANT_OUTDOORS,
		
		
		//Book actions.
		GET_KNOWLEDGE, GET_CRAFTY, GET_POTIONY, GET_RITUALS,		
		//Poisonous actions
		GET_POISONOUS_PLANT_GREENHOUSE, GET_NOXIOUS_PLANT_GREENHOUSE, 
		GET_POISONOUS_PLANT_OUTDOORS, GET_NOXIOUS_PLANT_OUTDOORS, GET_FROG,
		POISON_FOOD, POISON_WINE_CELLAR, POISON_WINE_KITCHEN,
		
		//Drunk goals
		DRINKING_CELLAR, DRINKING_HALL, DRINKING_KITCHEN, GATHER_ALCOHOL,
		
		//MURDEROUS!!!
		ASSAULT, CLEANUP, DEFENSIVE_KILL,
		
		//Sabotage. Cliff stalker has the character waiting at cliff for a victim so that they can be pushed off.
		LOOSEN_CHANDELIER, CLIFF_STALKER, CRAFTING_BOMB, LOOSEN_BALCONY, BALCONY_STALKER, GET_WRENCH, GET_SCREWDRIVER, GET_HAMMER,		
		
}
