package edu.pacific.comp55.starter;

public enum Goal {
		EATING, SLEEPING, BREWING_POISON, BREWING_ANTIDOTE, BREWING_PERFUME,
		RANSACK, GET_KNIFE, CRAFTING_LOCKPICK, CRAFTING_PISTOL, 
		ASSAULT, GET_RIFLE, GET_SWORD, DRINKING_CELLAR,
		DRINKING_HALL, DRINKING_KITCHEN, OOHSHINY, GOSSIPING,
	
}
